apiVersion: v1
kind: Pod
metadata:
  name: aks-kv-sample-pod
  labels:
    app: aks-kv-demo
    aadpodidbinding: "demo_app"
spec:
  containers:
    - name: aks-kv-container
      image: christianhxc/modernapp:1.1
      imagePullPolicy: Always
      ports:
        - containerPort: 80
      volumeMounts:
        - name: kvvolume
          mountPath: /kv
          readOnly: true
  volumes:
    - name: kvvolume
      flexVolume:
        driver: "azure/kv"
        options:
          usepodidentity: "true"
          keyvaultname: "msignitefrcma"
          keyvaultobjectnames: "secretone;secrettwo"
          keyvaultobjecttypes: "secret;secret"
          resourcegroup: "msignite-migration"
          subscriptionid: "00000000-0000-0000-0000-000000000000"
          tenantid: "00000000-0000-0000-0000-000000000000"
