apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentity
metadata:
  name: msignite
spec:
  type: 0
  ResourceID: /subscriptions/ece781f9-3b74-475c-a7b1-124bf2c313b0/resourcegroups/msignite-migration/providers/Microsoft.ManagedIdentity/userAssignedIdentities/msignite
  ClientID: 2429d07c-571f-4c55-be28-8b63d630120e
---
apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentityBinding
metadata:
  name: msignitebind
spec:
  AzureIdentity: msignite
  Selector: demo_app