apiVersion: v1
kind: Pod
metadata:
  name: sample-pod
  labels:
    aadpodidbinding: demo_app
spec:
  restartPolicy: Never
  containers:
    - name: auditlog-cleaner 
      image: christianhxc/modernapp:1.1
      imagePullPolicy: Always
      ports:
      - containerPort: 80
